###
# @name createEvent
POST http://localhost:3000/events
Content-Type: application/json

{
  "name": "Evento 1",
  "description": "This is a new event",
  "date": "2024-07-16T22:59:56.096Z",
  "price": 1000
}

###
@eventId = {{ createEvent.response.body.id }}

### listar todos os eventos
GET http://localhost:3000/events

### obter evento por id
GET http://localhost:3000/events/{{eventId}}

### atualizar evento por id
PATCH  http://localhost:3000/events/{{eventId}}
Content-Type: application/json

{
  "name": "Evento 1",
  "description": "This is a new event updated",
  "date": "2024-07-16T22:59:56.096Z",
  "price": 1000
}

### atualizar evento por id
DELETE   http://localhost:3000/events/{{eventId}}

###

