###
# @name createEvent
POST http://localhost:3000/events
Content-Type: application/json

{
  "name": "Evento 1000",
  "description": "This is a new event",
  "date": "2024-07-16T22:59:56.096Z",
  "price": 1000
}

###
@eventId = {{ createEvent.response.body.id }}

### 
GET http://localhost:3000/events

### 
GET http://localhost:3000/events/{{eventId}}

### 
PATCH  http://localhost:3000/events/{{eventId}}
Content-Type: application/json

{
  "name": "Evento 1",
  "description": "This is a new event updated",
  "date": "2024-07-16T22:59:56.096Z",
  "price": 1000
}

### atualizar evento por id
DELETE   http://localhost:3000/events/{{eventId}}

### SPOT
# @name createSpot
POST http://localhost:3000/events/{{eventId}}/spots
Content-Type: application/json

{
  "name": "B3"
}

###
@spotId = {{ createSpot.response.body.id }}

###
GET http://localhost:3000/events/{{eventId}}/spots

### 
GET http://localhost:3000/events/{{eventId}}/spots/{{spotId}}

### 
PATCH  http://localhost:3000/events/{{eventId}}/spots/{{spotId}}
Content-Type: application/json

{
  "name": "B2"
}

### 
DELETE http://localhost:3000/events/{{eventId}}/spots/{{spotId}}


###
@spotName = {{createSpot.response.body.name}}

POST http://localhost:3000/events/{{eventId}}/reserve
Content-Type: application/json
X-Api-Token: 123

{
  "spots": ["{{ spotName }}"],
  "ticket_kind": "full",
  "email": "test@test.com"
}
